namespace Iridio.Tokenization
{
    public enum SimpleToken
    {
        Comma,
        Equal,
        Number,
        Semicolon,
        Identifier,
        Echo,
        Text,
        CloseParen,
        OpenParen,
        Exclamation,
        Colon,
        OpenBracket,
        CloseBracket,
        CloseBrace,
        OpenBrace,
        EqualEqual,
        Greater,
        Less,
        GreaterOrEqual,
        LessOrEqual,
        If,
        Else,
        NotEqual,
        AnythingButBrackets
    }
}