namespace Iridio.Tokenization
{
    public enum SimpleToken
    {
        Comma,
        Equal,
        Integer,
        Semicolon,
        Identifier,
        Echo,
        Text,
        CloseParen,
        OpenParen,
        Exclamation,
        Colon,
        OpenBracket,
        CloseBracket,
        CloseBrace,
        OpenBrace,
        EqualEqual,
        Greater,
        Less,
        GreaterOrEqual,
        LessOrEqual,
        If,
        Else,
        NotEqual,
        Double,
        And,
        Or,
        Plus,
        Hyphen,
        Asterisk,
        Slash,
        False,
        True
    }
}